### ISSUE TITLE
Ping One SSO Error - "Din't recognize the email address you are using"

### ISSUE THREAD

**Issue by akshay-sarkar** [pingidentity/angular-spa-sample#3] opened 2018-08-16 16:27 UTC
Am trying to use this repository to connect with Ping One as Identity Provider.

I have done the following changes in environment.ts file,
```
export const environment: AuthorizationConfig & GeneralEnvironmentInfo  = {
  production: false,
  issuer_uri: 'https://sso.connect.pingidentity.com',
  client_id: '--------------------------',
  client_secret: '----------------------',
  //client_id: '465844544800-f1k5bhu8jibs9vc1ifh7nmhpmh7nqnod.apps.googleusercontent.com',
  redirect_uri: 'https://localhost:4200/callback',
  extras: {
    'prompt': 'consent',
    'access_type': 'offline'
  }
};
```
and in  Authentication_Service_configuration.ts of "node_modules\@openid\appauth\built",
```
var WELL_KNOWN_PATH = 'sso/sp';
var OPENID_CONFIGURATION = 'initsso?saasid=XXXXXXXX-XXXX-XXXX-a90c-b803f008edc2&idpid=701c8fab-XXXX-4f6d-8115-XXXXX';
```

Am able to move the user to Ping One Sign In page, but getting the following [error](https://drive.google.com/file/d/1c0EKiQ0OsUmiR1nqUSHkyKS-rlkSgzzr/view?usp=sharing).

Kindly let me know what other change is needed in the implementation to complete.

**Comment by dwaite** [comment] 2018-08-16 18:51
I admittedly have not tried yet against our new openid connect support, but try a issuer_uri of `https://sso.connect.pingidentity.com/{saasid}`, which should result in appauth fetching metadata at `https://sso.connect.pingidentity.com/{saasid}/.well-known/openid-configuration`. You shouldn't need to make those changes within the appauth code.

**Comment by dwaite** [comment] 2018-08-17 07:48
I am attempting to reproduce.

Have you performed some other change to work around the lack of a `Access-Control-Allow-Origin` header while fetching the metadata?

**Comment by akshay-sarkar** [comment] 2018-08-17 13:54
Yes, I have used the [CORS extension ](https://chrome.google.com/webstore/detail/cors/dboaklophljenpcjkbbibpkbpbobnbld)in chrome to handle it. 
Just switched it on before making the request to Ping-One Server.

**Comment by dwaite** [comment] 2018-08-17 21:03
In Chrome, I started with --disable-web-security --user-data-dir rather than installing an extension. Safari has an option under the ‘Develop’ menu to defer it as well, but I am using Chrome devtools and the remote debugger :-)

I’m diagnosing another issue with the app (looks like the token request is failing in a way I’m not logging to console), but I can explain how to possibly get farther while you wait:

On the authentication flow tab for the app, there is an initiate single sign-on URL with the sassid and idpid parameters. This is a non-OAuth feature which indicates that the next request will be for a particular tenant.

These parameters appear to also be able to be tacked on to the request to the token endpoint to skip the validation screen, but they are not in the openid-configuration metadata by default.

If you set the Start SSO URL to https://localhost:4200/ <https://localhost:4200/> and then go to the Initiate Single Sign-on URL, that will hit PingOne, indicate the tenant, and redirect to the app. Then attempting to sign in should redirect back, possibly ask for the userid and password, and send the browser back with the code and state. At this point I’m hitting an issue locally which I still need to diagnose.

Will update once I know more.

**Comment by dwaite** [comment] 2021-06-20 06:27
Closing due to age. Please reopen if this still does not work.

**Closed by dwaite** 2021-06-20 06:27 UTC
